require("chem")

a=Chem:create("Si Si H H H")
b=Chem:create("N N N H H H H")
c=Chem:create("Fe Fe Fe H H H H H")
Build:placeBlock(1,1,1,c)
Build:placeBlock(3,2,2,a)
Build:placeBlock(3,3,2,b)
Build:placeBlock(3,4,2,c)
r = Build:make()
Unit:deploy(r,1)
